version: '2'

services:
 guacamole-client:
  extends:
   file: ./docker-compose.yml
   service: guacamole-client
  build: ./canva/guacamole-client
  image: nanocloud/guacamole-client

 guacamole-server:
  extends:
   file: ./docker-compose.yml
   service: guacamole-server
  build: ./guacd
  image: nanocloud/guacamole-server

 nanocloud-backend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-backend
  build: ../nanocloud
  volumes_from:
   - nanocloud-frontend
  image: nanocloud/nanocloud-backend

 nanocloud-frontend:
  build: ../webapp
  extends:
   file: ./docker-compose.yml
   service: nanocloud-frontend
  volumes:
   - /opt/front
  container_name: "nanocloud-frontend"
  image: nanocloud/nanocloud-frontend

 proxy:
  extends:
   file: ./docker-compose.yml
   service: proxy
  build: ./nginx
  ports:
   - 80:80
   - 443:443
  image: nanocloud/proxy
  depends_on:
   - nanocloud-backend

 iaas-module:
  extends:
   file: ./docker-compose.yml
   service: iaas-module
  build: ./iaas
  image: nanocloud/iaas-module

 postgres:
  extends:
   file: ./docker-compose.yml
   service: postgres

networks:
 nanocloud:
  driver: bridge
