version: '2'

services:
 guacamole-client:
  extends:
   file: ./docker-compose.yml
   service: guacamole-client
  build:
   context: ./canva/guacamole-client
   dockerfile: Dockerfile-dev
  image: nanocloud/guacamole-client:dev
  ports:
   - 8000:8000
  volumes:
   - ./canva/guacamole-client/:/opt
   - ./canva/guacamole-client/noauth-logged/target/:/etc/guacamole/extensions/

 guacamole-server:
  extends:
   file: ./docker-compose.yml
   service: guacamole-server
  build: ./guacd
  image: nanocloud/guacamole-server:dev

 nanocloud-backend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-backend
  build:
   context: ../nanocloud
   dockerfile: Dockerfile-dev
  volumes_from:
   - nanocloud-frontend
  volumes:
   - ../nanocloud:/go/src/github.com/Nanocloud/community/nanocloud/
  image: nanocloud/nanocloud-backend:dev

 nanocloud-frontend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-frontend
  volumes:
   - /opt/front
  build:
   context: ../webapp
   dockerfile: Dockerfile-dev
  volumes:
   - ../webapp/:/opt/front
   - ./nginx/conf/certificates:/opt/ssl/:ro
  ports:
   - 49153:49153
   - 4201:4201
  restart: always
  container_name: "nanocloud-frontend"
  image: nanocloud/nanocloud-frontend:dev

 proxy:
  extends:
   file: ./docker-compose.yml
   service: proxy
  build: ./nginx
  image: nanocloud/proxy:dev
  ports:
   - 80:80
   - 443:443

 postgres:
  extends:
   file: ./docker-compose.yml
   service: postgres

 postgres:
  extends:
   file: ./docker-compose.yml
   service: postgres

 iaas-module:
  extends:
   file: ./docker-compose.yml
   service: iaas-module
  build:
   context: ./iaas
   dockerfile: Dockerfile-dev
  image: nanocloud/iaas-module:dev
  volumes:
   - ./iaas/:/go/src/github.com/Nanocloud/community/modules/iaas/
   - ./iaas/scripts/:/var/lib/nanocloud/scripts
   - ../installation_dir/images:/var/lib/nanocloud/images

networks:
 nanocloud:
  driver: bridge
