guacamole-client:
 extends:
  file: ./docker-compose.yml
  service: guacamole-client

guacamole-server:
 extends:
  file: ./docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-backend
 volumes_from:
  - nanocloud-frontend

nanocloud-frontend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-backend
 volumes:
  - /opt/front

proxy:
 extends:
  file: ./docker-compose.yml
  service: proxy

rabbitmq:
 extends:
  file: ./docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./docker-compose.yml
  service: postgres

apps-module:
 extends:
  file: ./docker-compose.yml
  service: apps-module

history-module:
 extends:
  file: ./docker-compose.yml
  service: history-module

iaas-module:
 extends:
  file: ./docker-compose.yml
  service: iaas-module

ldap-module:
 extends:
  file: ./docker-compose.yml
  service: ldap-module

users-module:
 extends:
  file: ./docker-compose.yml
  service: users-module
