version: '2'

services:
 guacamole-client:
  restart: always
  container_name: "guacamole-client"
  networks:
   - nanocloud

 nanocloud-backend:
  environment:
   - ENV=production
   - DATABASE_URI=postgres://nanocloud@postgres/nanocloud?sslmode=disable
   - PORT=8080
   - FRONT_DIR=/opt/front/dist
   - WIN_PASSWORD=Nanocloud123+
   - IAAS=qemu
   - WIN_USER=Administrator
   - PLAZA_ADDRESS=iaas-module
   - LDAP_SERVER_URI=ldaps://Administrator:Nanocloud123+@iaas-module:6360
   - BASE=DC=intra,DC=localdomain,DC=com
   - LDAP_USERNAME=CN=Administrator,CN=Users,DC=intra,DC=localdomain,DC=com
   - BIND_DN=CN=Administrator,DC=intra,DC=localdomain,DC=com
   - USER=Administrator
   - RDP_PORT=3389
   - SERVER=iaas-module
   - PASSWORD=Nanocloud123+
   - WINDOWS_DOMAIN=intra.localdomain.com
   - EXECUTION_SERVERS=iaas-module
   - TRUST_PROXY=true
   - ADMIN_FIRSTNAME=Admin
   - ADMIN_LASTNAME=Nanocloud
   - ADMIN_MAIL=admin@nanocloud.com
   - ADMIN_PASSWORD=admin
  restart: always
  container_name: "nanocloud-api"
  networks:
   - nanocloud

 guacamole-server:
  restart: always
  container_name: "guacamole-server"
  networks:
   - nanocloud

 nanocloud-frontend:
  container_name: "nanocloud-webapp"
  volumes:
   - /opt/front
  networks:
   - nanocloud

 proxy:
  restart: always
  container_name: "proxy"
  networks:
   - nanocloud

 postgres:
  image: postgres:9.5
  environment:
   - PGDATA=/var/lib/postgresql/data/pgdata
   - POSTGRES_USER=nanocloud
  restart: always
  container_name: "postgres"
  networks:
   - nanocloud

 iaas-module:
  environment:
   - ENV=production
   - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
   - INSTALLATION_DIR=/var/lib/nanocloud
   - SSH_PORT=1119
   - PASSWORD=Nanocloud123+
   - SERVER=localhost
   - USER=Administrator
   - ARTIFACT_URL=http://releases.nanocloud.org:8080/releases/0.7.0/
  devices:
   - /dev/kvm
  restart: always
  container_name: "iaas-module"
  networks:
   - nanocloud

networks:
 nanocloud:
  driver: bridge
