version: '2'

services:
 guacamole-client:
  extends:
   file: ./modules/docker-compose.yml
   service: guacamole-client
  image: nanocloud/guacamole-client:0.7.0

 guacamole-server:
  extends:
   file: ./modules/docker-compose.yml
   service: guacamole-server
  container_name: "guacamole-server"
  image: nanocloud/guacamole-server:0.7.0

 nanocloud-backend:
  extends:
   file: ./modules/docker-compose.yml
   service: nanocloud-backend
  volumes_from:
   - nanocloud-frontend
  image: nanocloud/nanocloud-backend:0.7.0

 nanocloud-frontend:
  extends:
   file: ./modules/docker-compose.yml
   service: nanocloud-frontend
  container_name: "nanocloud-frontend"
  volumes:
   - /opt/front
  image: nanocloud/nanocloud-frontend:0.7.0

 proxy:
  extends:
   file: ./modules/docker-compose.yml
   service: proxy
  ports:
   - 80:80
   - 443:443
  image: nanocloud/proxy:0.7.0
  depends_on:
   - nanocloud-backend

 postgres:
  extends:
   file: ./modules/docker-compose.yml
   service: postgres

 iaas-module:
  extends:
   file: ./modules/docker-compose.yml
   service: iaas-module
  image: nanocloud/iaas-module:0.7.0

networks:
 nanocloud:
  driver: bridge
