version: '2'

services:
 guacamole-client:
  extends:
   file: ./modules/docker-compose.yml
   service: guacamole-client
  image: nanocloud/guacamole-client

 guacamole-server:
  extends:
   file: ./modules/docker-compose.yml
   service: guacamole-server
  container_name: "guacamole-server"
  image: nanocloud/guacamole-server

 nanocloud-backend:
  extends:
   file: ./modules/docker-compose.yml
   service: nanocloud-backend
  volumes_from:
   - nanocloud-frontend
  image: nanocloud/nanocloud-backend

 nanocloud-frontend:
  extends:
   file: ./modules/docker-compose.yml
   service: nanocloud-frontend
  container_name: "nanocloud-frontend"
  volumes:
   - /opt/front
  image: nanocloud/nanocloud-frontend:latest

 proxy:
  extends:
   file: ./modules/docker-compose.yml
   service: proxy
  ports:
   - 80:80
   - 443:443
  image: nanocloud/proxy

 iaas-module:
  extends:
   file: ./modules/docker-compose.yml
   service: iaas-module
  image: nanocloud/iaas-module

 postgres:
  extends:
   file: ./modules/docker-compose.yml
   service: postgres

networks:
 nanocloud:
  driver: bridge
